export default {
    TEXT_LARGE: 34,
    TEXT_BIG: 28,
    TEXT_MEDIUM: 20,
    TEXT_SMALL: 16,
    TEXT_LITTLE: 14,

    PADDING_LARGE: 34,
    PADDING_BIG: 24,
    PADDING_MEDIUM: 20,
    PADDING_SMALL: 16,
    PADDING_LITTLE: 12,

    CELL_SIZE: 55.8,
    CELL_BORDER_RADIUS: 8,
    // DEFAULT_CELL_BG_COLOR: '#fff'
    // NOT_EMPTY_CELL_BG_COLOR: '#3557b7'
    // ACTIVE_CELL_BG_COLOR: '#f7fafe'
};
