export default {
    DATA: [
        {
            id: 'bd7acbea-c1b1-46c2-aed5-3ad53abb28ba',
            title: 'Российская Федерация',
        },
        {
            id: '3ac68afc-c605-48d3-a4f8-fbd91aa97f63',
            title: 'США',
        },
        {
            id: '58694a0f-3da1-471f-bd96-145571e29d72',
            title: 'Бразилия',
        },
    ],
    header: 'Авторизация',
    instruction: 'Выберите пожалуйста код страны и затем введите свой номер телефона',
    phoneIndex: '+7',
    placeHolder: 'Номер телефона',
    buttonTextNext: 'Продолжить',
    buttonTextNextGuest: 'Продолжить как гость',
    headerVerification: 'Введите Код',
    instructionVerification: 'Мы отправили одноразовый код \nна ваш телефон',
    buttonTextContinue: 'Продолжить',
    buttonTextRetry: 'Выслать повторно',
    cellCount: 5,
    headerMain: 'Appostrof',
    textRating: 'Рейтинг',
    scoreRating: '8.9/10',
    textDuration: 'Длительность',
    duration: '1ч 12мин',
    textComplete: 'Прочитано',
    completePercent: '12%',
    textMystic: 'Мистика',
    textThriller: 'Триллер',
    textRomance: 'Роман',
};
